### ISSUE TITLE
Is obs2vagrant dead?

### ISSUE THREAD

**Issue by peterdd** [flavio/obs2vagrant#8]
And if yes, what are the alternatives to build a (minimal) vagrant box from an official opensuse 15.1 release?

Some links in the Readme.md are broken: 
- https://godoc.org/github.com/flavio/obs2vagrant
- http://opensuse.github.io/kiwi/
- https://atlas.hashicorp.com/
- http://download.suse.de
- http://getgb.io/

I find some opensuse 15.1 boxes on https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=opensuse+15.1

But how do I get at least a little bit of trust on such boxes?

**Comment by flavio** [comment]
I'm not working on this project anymore. The openSUSE folks are publishing official vagrant images [here](https://app.vagrantup.com/opensuse). This is the source of trust for images.

Right now I don't see any 15.1 image, which seems strange. I suggest you to reach out to the openSUSE community via one if its mailing list/forums.
